imagePullSecrets: []
imagePullPolicy: Always

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

controller:
  resources:
    requests:
      memory: 256M
      cpu: 200m

recipes: {}


