apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-controller
  labels:
    {{- include "bakery-platform.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bakery-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: bakery
      labels:
        {{- include "bakery-platform.selectorLabels" . | nindent 8 }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: bakery-controller
        image: "bakery-controller:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v3/health
            port: 8080
        livenessProbe:
          httpGet:
            path: /api/v3/health
            port: 8080
        resources:
          {{- toYaml .Values.controller.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
